# Generated by Django 3.0.4 on 2020-03-23 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='state',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='contacts',
            old_name='zipcode',
            new_name='postalcode',
        ),
    ]
